"""create campaign_concurrency

Revision ID: 2b601c872658
Revises: cb068388bb5a
Create Date: 2026-06-21 21:07:04.648497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b601c872658'
down_revision: Union[str, Sequence[str], None] = 'cb068388bb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_concurrency',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_concurrency')
    # ### end Alembic commands ###
