"""add provider_call_id to call_tasks

Revision ID: 49b9ed1a6d93
Revises: 2b601c872658
Create Date: 2026-06-22 06:38:03.069108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49b9ed1a6d93'
down_revision: Union[str, Sequence[str], None] = '2b601c872658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_tasks', sa.Column('provider_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_tasks', 'provider_call_id')
    # ### end Alembic commands ###
