"""create provider_events and outcomes

Revision ID: 7facc9da2a48
Revises: 49b9ed1a6d93
Create Date: 2026-06-22 07:38:02.652426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7facc9da2a48'
down_revision: Union[str, Sequence[str], None] = '49b9ed1a6d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_events',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_task_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('transcript_s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_task_id'], ['call_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_call_task_id'), 'outcomes', ['call_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_call_task_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_table('provider_events')
    # ### end Alembic commands ###
