"""create call_tasks

Revision ID: cb068388bb5a
Revises: 440f79ccff62
Create Date: 2026-06-21 20:28:58.140409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb068388bb5a'
down_revision: Union[str, Sequence[str], None] = '440f79ccff62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_eligible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_index(op.f('ix_call_tasks_campaign_id'), 'call_tasks', ['campaign_id'], unique=False)
    op.create_index('ix_call_tasks_status_next_eligible', 'call_tasks', ['status', 'next_eligible_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_tasks_status_next_eligible', table_name='call_tasks')
    op.drop_index(op.f('ix_call_tasks_campaign_id'), table_name='call_tasks')
    op.drop_table('call_tasks')
    # ### end Alembic commands ###
